services:
  postgres:
    image: postgres:latest
    container_name: postgres_langgraph_memory
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: langgraph_memory
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: